---
abstract: 'Subclass of Archive::Tar that deals with Android Backup files (adb backup / adb restore)'
author:
  - 'Nathaniel Lally <nll@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Archive-AndroidBackup
no_index:
  directory:
    - t
    - inc
requires:
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::NonMoose: 0
  Test::Version: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Archive-AndroidBackup
  license: http://www.gnu.org/copyleft/gpl.html
version: 1.14
